### ISSUE TITLE
remove option

### ISSUE THREAD

**Issue by SupremeBob** [eve-echoes-botting/blocklistbot#1]
needs a way to remove blacklist entries, thx

**Comment by github-4o** [comment]
Ok. Let's get this down to specifics @SupremeBob 
Is `@<botname> blocklist rm <either name or tag>` ok with you?

**Comment by github-4o** [comment]
Test msg

**Comment by SupremeBob** [comment]
for boomers like me the verbose "remove" is actually more intuitive

**Comment by github-4o** [comment]
The rest is ok?

**Comment by github-4o** [comment]
> for boomers like me the verbose "remove" is actually more intuitive

The rest is ok?

**Comment by SupremeBob** [comment]
more issues coming, the other leads chipped in with more requirements sry

**Comment by github-4o** [comment]
Remove format fine with you?

**Comment by SupremeBob** [comment]
the syntax part `<either name or tag>` ?
make it `<name or id>` please, so it's consistent with the other changes

**Comment by github-4o** [comment]
`@<botname> blocklist remove <name or id>`?

**Comment by SupremeBob** [comment]
yes
