### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by SupremeBob** [eve-echoes-botting/blocklistbot#2]
name needs to be changed from "blocklist" to "blacklist", as that's what it's called in SRN

**Comment by github-4o** [comment]
Sorry, hard no for this. I see why you ask this and I even agree with you. But times changed. Even here on GitHub stable branch was renamed to `main`. Used to be `master`

**Comment by SupremeBob** [comment]
I don't fully understand this, is there a limitation that prevents you from renaming the bot feature, possibly by making it a new copy? we can work with "blocklist" if that's a hard no, no problem

**Comment by github-4o** [comment]
There are no technical obstacles to using blacklist for a name. I just want to honor the tolerance movement

**Comment by SupremeBob** [comment]
Understood.
