### ISSUE TITLE
values stored in context to entries

### ISSUE THREAD

**Issue by SupremeBob** [eve-echoes-botting/blocklistbot#4]
required values per pilot:
- pilot ingame name
- pilot ingame ID
- a reason
- nickname, example: [KSM] Super Bob (not discord handle) of the discord user who added the entry
- date the entry was added on

**Comment by github-4o** [comment]
How is this different from current fields?

**Comment by SupremeBob** [comment]
I didn't see the entries when showing an empty list, if they're all there I will make a new issue about using these values

**Comment by SupremeBob** [comment]
found the part I was looking for
![image](https://github.com/eve-echoes-botting/blocklistbot/assets/152234526/038893f6-7aa2-4af5-a752-9d0c8386de19)

we're looking to see the following instead

```
manually entered fields
pilot name: <text>
pilot id: <text>
reason: <text>

automatically generated fields
added by <discord nickname> // if possible, auto grab the nick (not discord handle) of the person making the entry here
added: <date> // if possible automate the date upon entry here
```

**Comment by github-4o** [comment]
So
Rename initial pilot name to pilot name
Rename pilot tag number to pilot I'd
Rename reason blacbla to just reason
Remove everything else

**Comment by SupremeBob** [comment]
yes, the author and date can be automated?

**Comment by github-4o** [comment]
![Screenshot_2023-11-29-11-10-20-727](https://github.com/eve-echoes-botting/blocklistbot/assets/18388252/b81b7d94-fb25-4538-afeb-32c47327fae6)

**Comment by SupremeBob** [comment]
that's great, no need for the id here
![image](https://github.com/eve-echoes-botting/blocklistbot/assets/152234526/4ab89a02-afbd-4470-89cc-27cf241eadeb)

**Comment by github-4o** [comment]
You sure no need for id? Disco names could be easily changed

**Comment by SupremeBob** [comment]
OK if you see a reason for it, you can leave it in

**Comment by github-4o** [comment]
Ok let me do some git magic that should automatically close this issue
